### ISSUE TITLE
openapi-typescript-codegen fails on a oneOf instance

### ISSUE THREAD

**Issue by rbruggem** [lune-climate/openapi-typescript-codegen#40]
Version: 0.0.14.

The following schema:

```
    SetBundlePortfolioRequest:
      oneOf:
        - type: object
          required:
            - bundle_portfolio_id
          properties:
            bundle_portfolio_id:
              type: string
              example: 'j85vWbLVZNlOayV94P8AM1K29RgJq4xX'
        - type: object
          required:
            - slug
          properties:
            slug:
              type: string
              description: Slug of the bundle portfolio.
              example: 'oxford-offsetting-principles'
```
generates the following function signature:

```
 43      * @returns BundlePortfolio OK
 44      */
 45     public updateBundlePortfolio(
 46         data: {
 47             ?: {
 48                 bundlePortfolioId: string;
 49             };
 50             ?: {
 51                 /**
 52                  * Slug of the bundle portfolio.
 53                  */
 54                 slug: string;
 55             };
 56         },
 57         options?: {
 58             /**
 59              * Account Id to be used to perform the API call
 60              */
 61             accountId?: string;
 62         },
 63     ): Promise<Result<BundlePortfolio, ApiError>> {
 64         return __request(this.client, this.config, options || {}, {
 65             method: 'PUT',
```

Notice line 47 and 50.
